import type { Locale } from "@/lib/i18n";

export const discoveryKinds = ["concern", "routine", "ingredient"] as const;
export type DiscoveryKind = (typeof discoveryKinds)[number];

export const discoveryPaths: Record<DiscoveryKind, string> = {
  concern: "concerns",
  routine: "routines",
  ingredient: "ingredients",
};

export type DiscoveryRecord = {
  slug: string;
  title: string;
  subtitle: string;
  summary: string;
  signals: string[];
  chapters: Array<[string, string]>;
  watchouts: string[];
  related: Array<[string, string, string]>;
  faqs: Array<[string, string]>;
};

export const discoveryHubCopy = {
  ar: {
    concern: { eyebrow: "CONCERN COMPASS", title: "ابدئي من السؤال.\nلا من اسم المنتج.", intro: "نفكك الاحتياج إلى إشارات واضحة ومسار بسيط، من دون تشخيص ذاتي أو وعود مبالغ فيها.", decisionTitle: "النتيجة تبدأ بالفهم.", decisionBody: "اختاري المسار الأقرب لما تريدين تحسينه، ثم اقرئي الحدود والخطوات قبل الانتقال إلى أي منتج.", nextLabel: "افهمي المكوّنات", nextHref: "/ingredients" },
    routine: { eyebrow: "RITUAL ATLAS", title: "روتينك إيقاع.\nلا رف كامل.", intro: "مسارات قصيرة ترتب الخطوات حسب اللحظة والهدف، وتبقي كل إضافة مرتبطة بدور واضح.", decisionTitle: "اختاري اللحظة أولًا.", decisionBody: "الصباح، المناسبة أو ما بعد الاستحمام؛ عندما تتضح اللحظة يصبح ترتيب الخطوات أبسط.", nextLabel: "اكتشفي حسب الاحتياج", nextHref: "/concerns" },
    ingredient: { eyebrow: "INGREDIENT LIBRARY", title: "المكوّن مفهوم.\nلا موضة.", intro: "اقرئي الدور والملاءمة والحدود قبل أن يتحول اسم المكوّن إلى قرار شراء.", decisionTitle: "الدور أهم من الاسم.", decisionBody: "قيمة المكوّن تظهر داخل قوام وتوقيت وروتين كامل، وليست وعدًا منفصلًا.", nextLabel: "اكتشفي العناية بالبشرة", nextHref: "/shop/skincare" },
    directory: "EXPLORE THE DIRECTORY",
    directoryTitle: "مسارات قليلة.\nوأسئلة أوضح.",
    signalLabel: "إشارات البداية",
    openLabel: "افتحي المسار",
    closingEyebrow: "BEAUTY, CONSIDERED",
    closingTitle: "اختيارك التالي\nيبدأ من الوضوح.",
    conceptNotice: "محتوى إرشادي عام، وليس تشخيصًا طبيًا أو وعدًا بنتيجة.",
  },
  en: {
    concern: { eyebrow: "CONCERN COMPASS", title: "Begin with the question.\nNot the product name.", intro: "We break a need into clearer signals and a simpler path, without self-diagnosis or inflated promises.", decisionTitle: "A better result begins with understanding.", decisionBody: "Choose the route closest to what you want to improve, then read its limits and steps before any product.", nextLabel: "Understand ingredients", nextHref: "/ingredients" },
    routine: { eyebrow: "RITUAL ATLAS", title: "Your ritual is a rhythm.\nNot a full shelf.", intro: "Shorter paths arrange each step around the moment and purpose, keeping every addition accountable.", decisionTitle: "Choose the moment first.", decisionBody: "Morning, occasion or after shower; once the moment is clear, the order becomes simpler.", nextLabel: "Explore by concern", nextHref: "/concerns" },
    ingredient: { eyebrow: "INGREDIENT LIBRARY", title: "An ingredient, understood.\nNever a trend.", intro: "Read its role, fit and limits before an ingredient name becomes a buying decision.", decisionTitle: "Role matters more than name.", decisionBody: "An ingredient earns its place through texture, timing and a complete ritual — never as an isolated promise.", nextLabel: "Explore skincare", nextHref: "/shop/skincare" },
    directory: "EXPLORE THE DIRECTORY",
    directoryTitle: "Fewer routes.\nClearer questions.",
    signalLabel: "Starting signals",
    openLabel: "Open the route",
    closingEyebrow: "BEAUTY, CONSIDERED",
    closingTitle: "Your next choice\nbegins with clarity.",
    conceptNotice: "General educational content; not medical diagnosis or a promise of results.",
  },
} as const satisfies Record<Locale, unknown>;

export const discoveryDetailCopy = {
  ar: {
    chaptersEyebrow: "THE DECISION, IN PARTS", chaptersTitle: "افهمي الأدوار.\nثم رتّبي الخطوات.", watchEyebrow: "BEFORE YOU CONTINUE", watchTitle: "الحدود جزء\nمن القرار.", relatedEyebrow: "CONTINUE WITH INTENT", relatedTitle: "المسار التالي،\nمن دون قفزة عشوائية.", faqEyebrow: "A CLEARER ANSWER", faqTitle: "أسئلة قصيرة.\nوإجابات منضبطة.", back: "العودة إلى الدليل", disclaimer: "هذا المحتوى إرشادي عام. عند التهيج المستمر أو الأعراض المقلقة، استشيري مختصًا مؤهلًا.", breadcrumbHome: "الرئيسية" },
  en: {
    chaptersEyebrow: "THE DECISION, IN PARTS", chaptersTitle: "Understand the roles.\nThen order the steps.", watchEyebrow: "BEFORE YOU CONTINUE", watchTitle: "Limits belong\nin the decision.", relatedEyebrow: "CONTINUE WITH INTENT", relatedTitle: "The next route,\nwithout a random leap.", faqEyebrow: "A CLEARER ANSWER", faqTitle: "Short questions.\nDisciplined answers.", back: "Back to the guide", disclaimer: "This is general educational content. For persistent irritation or concerning symptoms, consult a qualified professional.", breadcrumbHome: "Home" },
  labels: {
    ar: { concern: "حسب الاحتياج", routine: "الروتينات", ingredient: "المكوّنات" },
    en: { concern: "By concern", routine: "Rituals", ingredient: "Ingredients" },
  },
} as const;

export const discoveryRecords: Record<Locale, Record<DiscoveryKind, DiscoveryRecord[]>> = {
  ar: {
    concern: [
      { slug: "pigmentation", title: "التصبغات", subtitle: "CONCERN · CLARITY FIRST", summary: "مسار هادئ لفهم الإشراقة وتوحيد مظهر البشرة من دون تحويل السؤال إلى تشخيص أو روتين مزدحم.", signals: ["تفاوت ظاهر في اللون", "الرغبة في روتين صباحي أوضح", "الحاجة إلى حماية يومية ثابتة"], chapters: [["ابدئي بالأساس", "تنظيف لطيف وترطيب مناسب يبقيان نقطة البداية قبل إضافة أي خطوة مركزة."], ["مكوّن واحد مفهوم", "أضيفي مكوّنًا واحدًا في كل مرة، واقرئي القوام والتوقيت بدل مطاردة الوعود."], ["الحماية اليومية", "ثبات الحماية في النهار أهم من تكديس خطوات لا يمكن الاستمرار عليها."]], watchouts: ["لا تحوّلي تغير اللون إلى تشخيص ذاتي.", "اختبري أي تركيبة جديدة تدريجيًا.", "توقفي واطلبي رأيًا مختصًا عند التهيج المستمر."], related: [["روتين صباحي للبشرة الدهنية", "خطوات مرتبة للصباح", "/routines/morning-routine-oily-skin"], ["فيتامين C", "فهم الدور والتوقيت", "/ingredients/vitamin-c"], ["نياسيناميد", "مسار توازن أبسط", "/ingredients/niacinamide"]], faqs: [["هل أحتاج روتينًا طويلًا؟", "لا. الوضوح والاستمرار أهم من عدد الخطوات."], ["هل هذه الصفحة تشخّص سبب التصبغات؟", "لا. هي دليل قرار عام ولا تستبدل تقييم المختص."]] },
      { slug: "makeup-longwear", title: "ثبات المكياج", subtitle: "CONCERN · LONGWEAR WITH COMFORT", summary: "فهم الثبات من خلال التحضير والقوام والمناسبة، من دون ربطه بطبقات ثقيلة أو وعود مطلقة.", signals: ["يوم طويل أو مناسبة", "تغير القاعدة مع الحرارة", "الحاجة إلى نتيجة مرتبة ومريحة"], chapters: [["تهيئة متوازنة", "سطح مريح وغير مثقل يساعد القاعدة على الاندماج بصورة أفضل."], ["قوام يناسب اللحظة", "اختاري النتيجة والتغطية بحسب اليوم بدل الاعتماد على كلمة طويل الثبات وحدها."], ["تثبيت موضعي", "ركّزي التثبيت على المناطق التي تحتاجه بدل إضافة طبقة كاملة بلا داعٍ."]], watchouts: ["الثبات لا يعني بالضرورة تغطية أثقل.", "اختبري توافق الطبقات قبل المناسبة.", "الدرجة الحقيقية تحتاج سواتشات وصورًا معتمدة."], related: [["روتين قاعدة المناسبات", "ترتيب التطبيق", "/routines/occasion-base-routine"], ["هيالورونيك أسيد", "الراحة والملمس", "/ingredients/hyaluronic-acid"], ["دليل الجمال", "قراءة أعمق قبل الاختيار", "/journal"]], faqs: [["هل الثبات يعني مظهرًا ثقيلًا؟", "لا؛ التحضير والقوام وطريقة التطبيق تؤثر بقدر عدد الطبقات."], ["هل يمكن حسم الدرجة هنا؟", "لا. الدرجة تحتاج تصويرًا وسواتشات معتمدة قبل القرار التجاري."]] },
    ],
    routine: [
      { slug: "morning-routine-oily-skin", title: "روتين صباحي للبشرة الدهنية", subtitle: "RITUAL · LIGHT MORNING RHYTHM", summary: "أربع لحظات بسيطة للصباح: تنظيف وراحة وخطوة مركزة واحدة ثم حماية يومية.", signals: ["البشرة الدهنية أو المختلطة", "الأجواء الحارة", "تفضيل قوام أخف"], chapters: [["01 · تنظيف لطيف", "ابدئي من دون إحساس بالشد أو تنظيف مفرط."], ["02 · خطوة مركزة واحدة", "اختاري دورًا واضحًا وأدخليه تدريجيًا."], ["03 · ترطيب متوازن", "قوام مريح ينسجم مع النهار."], ["04 · حماية يومية", "اختتمي بخطوة حماية مناسبة لاستخدامك."]], watchouts: ["أدخلي منتجًا جديدًا واحدًا في كل مرة.", "خففي الخطوات عند ظهور انزعاج.", "لا تستبدلي نصيحة المختص بروتين عام."], related: [["التصبغات", "ابدئي من الاحتياج", "/concerns/pigmentation"], ["فيتامين C", "دور صباحي محتمل", "/ingredients/vitamin-c"], ["العناية بالبشرة", "العودة إلى الفئة", "/shop/skincare"]], faqs: [["هل يجب تنفيذ الأربع يوميًا؟", "يمكن تبسيطها بحسب الحاجة مع الحفاظ على ترتيب منطقي."], ["أين المنتجات؟", "تُضاف فقط بعد اعتماد بيانات وصور الكتالوج الحقيقي."]] },
      { slug: "occasion-base-routine", title: "روتين قاعدة للمناسبات", subtitle: "RITUAL · OCCASION BASE", summary: "ترتيب مدروس للتهيئة والقاعدة والتثبيت يحافظ على الراحة والنتيجة المتوازنة.", signals: ["مناسبة أو يوم ممتد", "تغطية قابلة للبناء", "ثبات من دون مبالغة"], chapters: [["01 · تهيئة خفيفة", "ترطيب متوازن يترك سطحًا مريحًا."], ["02 · برايمر عند الحاجة", "أضيفيه فقط عندما يخدم النتيجة."], ["03 · قاعدة تدريجية", "ابني التغطية على مراحل بدل طبقة ثقيلة."], ["04 · تثبيت متوازن", "ثبتي المناطق الأكثر حاجة فحسب."]], watchouts: ["اختبري توافق القوام قبل المناسبة.", "لا تحسمي الدرجة من صورة مفاهيمية.", "خففي التثبيت إذا ظهر الجفاف."], related: [["ثبات المكياج", "فهم الاحتياج", "/concerns/makeup-longwear"], ["هيالورونيك أسيد", "الراحة داخل القوام", "/ingredients/hyaluronic-acid"], ["المكياج", "العودة إلى الفئة", "/shop/makeup"]], faqs: [["هل يصلح للنهار؟", "يمكن تبسيطه بحسب الوقت والنتيجة المطلوبة."], ["هل المنتجات معروضة؟", "لا، حتى اكتمال الصور والدرجات والبيانات المعتمدة."]] },
      { slug: "humidity-proof-hair-routine", title: "روتين تهدئة الهيشان بعد الغسيل", subtitle: "RITUAL · HUMIDITY AWARE", summary: "ترتيب أخف للفروة والأطراف يساعد على إدارة الملمس في الحرارة والرطوبة.", signals: ["هيشان بعد الغسيل", "رطوبة أو حرارة", "الحاجة إلى فصل الفروة عن الأطراف"], chapters: [["01 · تنظيف مريح", "نظفي الفروة دون إحساس قاسٍ."], ["02 · دعم الجذور", "وجهي العناية إلى مصدر الانزعاج عند الحاجة."], ["03 · ترطيب الأطراف", "استخدمي قوامًا لا يثقل الشعر."], ["04 · لمسة بعد التصفيف", "قللي الهيشان بخطوة صغيرة ومدروسة."]], watchouts: ["لا تكدسي القوام على الفروة.", "افصلي احتياج الجذور عن الأطراف.", "استشيري مختصًا عند أعراض فروة مستمرة."], related: [["العناية بالشعر", "العودة إلى الفئة", "/shop/haircare"], ["بانثينول", "الراحة والنعومة", "/ingredients/panthenol"], ["البحث", "مسار مباشر", "/search?q=haircare"]], faqs: [["هل يمنع الهيشان تمامًا؟", "لا؛ هو ترتيب عام يساعد على إدارة الملمس ولا يعد بنتيجة مطلقة."], ["هل الكتالوج مكتمل؟", "لا، المنتجات ستظهر بعد الاعتماد فقط."]] },
      { slug: "after-shower-body-routine", title: "روتين راحة الجسم بعد الاستحمام", subtitle: "RITUAL · AFTER SHOWER", summary: "عادة يومية بسيطة تبدأ من القوام المناسب وتركز على المناطق التي تحتاج راحة إضافية.", signals: ["جفاف بعد الاستحمام", "تفضيل ملمس غير لزج", "عادة شخصية أو فكرة هدية"], chapters: [["01 · اختاري القوام", "خفيف للأيام العملية أو أغنى للحظات الراحة."], ["02 · ركزي على المناطق الجافة", "اليدان والمرفقان والساقان قد تحتاج اهتمامًا أوضح."], ["03 · لمسة مكملة", "أضيفيها فقط إذا خدمت الراحة أو الرائحة الهادئة."], ["04 · مجموعة عند الحاجة", "حوّلي الروتين إلى هدية فقط عندما تكون المناسبة واضحة."]], watchouts: ["اختبري الملاءمة على مساحة صغيرة.", "القوام الغني لا يناسب كل وقت.", "التغليف والشحن يحتاجان اعتمادًا منفصلًا."] , related: [["العناية بالجسم", "العودة إلى الفئة", "/shop/bodycare"], ["زبدة الشيا", "فهم القوام الأغنى", "/ingredients/shea-butter"], ["الهدايا والمجموعات", "مسار الإهداء", "/shop/beauty-sets"]], faqs: [["هل هو للاستخدام اليومي؟", "يمكن تكييفه بحسب الحاجة والطقس."], ["هل يصلح كهدية؟", "نعم بعد اعتماد المجموعة والتغليف والمعلومات التشغيلية."]] },
    ],
    ingredient: [
      { slug: "niacinamide", title: "نياسيناميد", subtitle: "INGREDIENT · BALANCE", summary: "مكوّن يُقرأ داخل روتين متوازن وقوام مناسب، لا كحل شامل لكل احتياج.", signals: ["الرغبة في روتين أبسط", "توازن المظهر", "خطوة يومية واضحة"], chapters: [["الدور", "قد يخدم روتينًا يركز على التوازن والراحة العامة."], ["الملاءمة", "يُفهم أفضل داخل قوام وتوقيت واضحين."], ["المكان", "ابدئي بخطوة واحدة وراقبي الاستجابة."]], watchouts: ["ليس علاجًا مطلقًا.", "لا يكفي الاسم للحكم على التركيبة.", "اختبار التدرج أهم من تكديس المكونات."], related: [["التصبغات", "سياق الاحتياج", "/concerns/pigmentation"], ["روتين الصباح", "ترتيب الاستخدام", "/routines/morning-routine-oily-skin"], ["العناية بالبشرة", "العودة إلى الفئة", "/shop/skincare"]], faqs: [["متى يكون مدخلًا جيدًا؟", "عندما تبحثين عن روتين أبسط وتريدين فهم الدور قبل المنتج."], ["هل هو بديل عن المختص؟", "لا؛ المحتوى عام ولا يشخص أو يعالج."]] },
      { slug: "vitamin-c", title: "فيتامين C", subtitle: "INGREDIENT · MORNING RADIANCE", summary: "يُفهم ضمن روتين صباحي واضح يجمع القوام والتوقيت والحماية، دون وعود علاجية.", signals: ["نية إشراقة صباحية", "قوام خفيف للنهار", "الربط بالحماية اليومية"], chapters: [["الدور", "قد يدعم مسارًا يركز على مظهر أكثر إشراقًا."], ["التوقيت", "يُقرأ ضمن روتين صباحي بسيط."], ["السياق", "الحماية اليومية جزء أساسي من الصورة الكاملة."]], watchouts: ["لا يُقدم كعلاج للتصبغات.", "التركيبة والقوام أهم من الاسم وحده.", "أدخليه تدريجيًا عند الملاءمة."], related: [["التصبغات", "سياق الاحتياج", "/concerns/pigmentation"], ["روتين الصباح", "ترتيب الاستخدام", "/routines/morning-routine-oily-skin"], ["دليل الجمال", "قراءة أوسع", "/journal"]], faqs: [["لماذا يرتبط بالصباح؟", "لأن هذا المسار يشرح توقيتًا شائعًا داخل روتين متكامل، لا قاعدة طبية مطلقة."], ["هل النتيجة مضمونة؟", "لا؛ الاستجابة تختلف ولا توجد وعود نتائج هنا."]] },
      { slug: "hyaluronic-acid", title: "هيالورونيك أسيد", subtitle: "INGREDIENT · COMFORT AND TEXTURE", summary: "يُقرأ من زاوية الراحة والقوام والاندماج داخل العناية أو المكياج.", signals: ["راحة الملمس", "سهولة الدمج", "الربط بين العناية والقاعدة"], chapters: [["الدور", "يدخل عادة في سياقات ترتبط بالترطيب والراحة."], ["القوام", "الحكم يكون على التركيبة الكاملة لا اسم المكوّن."], ["الاندماج", "راقبي توافقه مع بقية الطبقات."]], watchouts: ["ليس دليلًا منفردًا على جودة المنتج.", "التطبيق يختلف حسب التركيبة.", "لا تضيفي طبقات بلا حاجة واضحة."], related: [["ثبات المكياج", "سياق القاعدة", "/concerns/makeup-longwear"], ["روتين المناسبات", "ترتيب الطبقات", "/routines/occasion-base-routine"], ["المكياج", "العودة إلى الفئة", "/shop/makeup"]], faqs: [["هل يخص العناية فقط؟", "لا؛ قد يظهر في سياقات مكياج أيضًا بحسب التركيبة."], ["هل الاسم يحسم القوام؟", "لا، القوام نتيجة التركيبة الكاملة."]] },
      { slug: "panthenol", title: "بانثينول", subtitle: "INGREDIENT · CALM AND SOFTNESS", summary: "مدخل لفهم الراحة والنعومة داخل روتين الشعر من دون وعود شاملة للفروة أو الأطراف.", signals: ["راحة بعد الغسيل", "نعومة الأطراف", "روتين شعر أخف"], chapters: [["الدور", "قد يخدم إحساس الراحة والنعومة داخل تركيبات مختلفة."], ["المكان", "حددي هل السؤال يبدأ من الفروة أم الأطراف."], ["القوام", "اختاري ما لا يثقل الشعر في استخدامك."]], watchouts: ["ليس حلًا شاملًا لكل مشاكل الشعر.", "السياق والتركيبة يحددان الملاءمة.", "أعراض الفروة المستمرة تحتاج مختصًا."], related: [["روتين الهيشان", "ترتيب ما بعد الغسيل", "/routines/humidity-proof-hair-routine"], ["العناية بالشعر", "العودة إلى الفئة", "/shop/haircare"], ["البحث", "استكشاف مباشر", "/search?q=panthenol"]], faqs: [["متى أبدأ منه؟", "عندما يكون السؤال عن الراحة أو النعومة وتريدين فهم الدور أولًا."], ["هل يعالج الفروة؟", "لا نقدم هذا الادعاء؛ الأعراض المستمرة تحتاج تقييمًا مناسبًا."]] },
      { slug: "shea-butter", title: "زبدة الشيا", subtitle: "INGREDIENT · RICHER COMFORT", summary: "قوام أغنى يُقرأ داخل عناية الجسم أو الإهداء وفق الطقس واللحظة، لا كحل واحد للجميع.", signals: ["راحة بعد الاستحمام", "قوام أغنى", "عناية يومية أو هدية"], chapters: [["الدور", "تدخل عادة في تركيبات أكثر غنى وراحة."], ["اللحظة", "قد تناسب أوقاتًا ومناطق أكثر جفافًا."], ["الإهداء", "تخدم المجموعة عندما يكون الاستخدام واضحًا."]], watchouts: ["القوام الغني لا يناسب كل وقت.", "لا تختزلي العناية بالجسم في مكوّن واحد.", "اختبري الملاءمة الفردية تدريجيًا."], related: [["روتين بعد الاستحمام", "ترتيب الاستخدام", "/routines/after-shower-body-routine"], ["العناية بالجسم", "العودة إلى الفئة", "/shop/bodycare"], ["الهدايا", "مسار المجموعة", "/shop/beauty-sets"]], faqs: [["هل تناسب الصيف؟", "يعتمد ذلك على القوام الكامل ووقت الاستخدام والتفضيل الفردي."], ["هل هي علاج للجفاف؟", "لا نقدم ادعاءً علاجيًا؛ المحتوى يشرح القوام والسياق فقط."]] },
    ],
  },
  en: {
    concern: [
      { slug: "pigmentation", title: "Uneven tone", subtitle: "CONCERN · CLARITY FIRST", summary: "A quieter route to understanding radiance and visible uneven tone without turning the question into diagnosis or an overcrowded ritual.", signals: ["Visible uneven tone", "A clearer morning ritual", "Consistent daily protection"], chapters: [["Begin with the foundation", "Gentle cleansing and suitable hydration come before any focused step."], ["One understood ingredient", "Introduce one role at a time and read texture and timing before promises."], ["Daily protection", "Consistency in the daytime matters more than steps you cannot sustain."]], watchouts: ["Do not turn colour change into self-diagnosis.", "Introduce new formulas gradually.", "Seek qualified advice for persistent irritation."], related: [["Morning ritual for oily skin", "An ordered morning path", "/routines/morning-routine-oily-skin"], ["Vitamin C", "Understand role and timing", "/ingredients/vitamin-c"], ["Niacinamide", "A simpler balance route", "/ingredients/niacinamide"]], faqs: [["Do I need a long ritual?", "No. Clarity and consistency matter more than step count."], ["Does this diagnose uneven tone?", "No. It is general decision support, not professional assessment."]] },
      { slug: "makeup-longwear", title: "Makeup longevity", subtitle: "CONCERN · LONGWEAR WITH COMFORT", summary: "Understand wear through preparation, texture and occasion without equating it with heavy layers or absolute promises.", signals: ["A long day or occasion", "Base changing in heat", "A composed, comfortable finish"], chapters: [["Balanced preparation", "A comfortable, unburdened surface helps the base integrate."], ["Texture for the moment", "Choose result and coverage for the day, not the word longwear alone."], ["Targeted setting", "Set only where needed instead of adding a full layer by default."]], watchouts: ["Longevity does not require heavier coverage.", "Test layer compatibility before an occasion.", "True shade choice needs approved swatches."], related: [["Occasion base ritual", "Order the application", "/routines/occasion-base-routine"], ["Hyaluronic acid", "Comfort and texture", "/ingredients/hyaluronic-acid"], ["Beauty journal", "Read further before choosing", "/journal"]], faqs: [["Does longwear mean heavy?", "No; preparation, texture and application matter as much as layer count."], ["Can I choose shade here?", "No. Shade needs approved imagery and true swatches."]] },
    ],
    routine: [
      { slug: "morning-routine-oily-skin", title: "Morning ritual for oily skin", subtitle: "RITUAL · LIGHT MORNING RHYTHM", summary: "Four simpler morning moments: cleanse, comfort, one focused step and daily protection.", signals: ["Oily or combination skin", "Warm weather", "A preference for lighter textures"], chapters: [["01 · Gentle cleanse", "Begin without tightness or aggressive cleansing."], ["02 · One focused step", "Choose one legible role and introduce it gradually."], ["03 · Balanced hydration", "A comfortable texture suited to daytime."], ["04 · Daily protection", "Complete the ritual with protection suited to your use."]], watchouts: ["Introduce one new product at a time.", "Reduce steps if discomfort appears.", "A general ritual does not replace qualified advice."], related: [["Uneven tone", "Begin with the concern", "/concerns/pigmentation"], ["Vitamin C", "A possible morning role", "/ingredients/vitamin-c"], ["Skincare", "Back to the category", "/shop/skincare"]], faqs: [["Must I do all four daily?", "Simplify according to need while keeping a sensible order."], ["Where are the products?", "They appear only after real catalogue data and imagery are approved."]] },
      { slug: "occasion-base-routine", title: "Occasion base ritual", subtitle: "RITUAL · OCCASION BASE", summary: "A considered order for preparation, base and setting that protects comfort and balance.", signals: ["An occasion or extended day", "Buildable coverage", "Wear without excess"], chapters: [["01 · Light preparation", "Balanced hydration leaves a comfortable surface."], ["02 · Primer when needed", "Add it only when it serves the result."], ["03 · Gradual base", "Build coverage in stages rather than one heavy layer."], ["04 · Balanced setting", "Set the areas that genuinely need it."]], watchouts: ["Test texture compatibility before the occasion.", "Never choose shade from a concept image.", "Reduce setting if dryness appears."], related: [["Makeup longevity", "Understand the concern", "/concerns/makeup-longwear"], ["Hyaluronic acid", "Comfort in texture", "/ingredients/hyaluronic-acid"], ["Makeup", "Back to the category", "/shop/makeup"]], faqs: [["Can this work for daytime?", "Yes; simplify it for the time and result you need."], ["Are products available here?", "Not until imagery, shades and approved catalogue data are complete."]] },
      { slug: "humidity-proof-hair-routine", title: "Post-wash frizz ritual", subtitle: "RITUAL · HUMIDITY AWARE", summary: "A lighter order for scalp and ends, shaped around texture in heat and humidity.", signals: ["Frizz after washing", "Heat or humidity", "Separating scalp from ends"], chapters: [["01 · Comfortable cleansing", "Clean the scalp without a harsh after-feel."], ["02 · Root support", "Direct care toward the origin of discomfort when relevant."], ["03 · Hydrate the ends", "Use a texture that does not burden the hair."], ["04 · A finishing touch", "Manage frizz with one small, considered step."]], watchouts: ["Avoid layering rich textures on the scalp.", "Separate root and end needs.", "Persistent scalp symptoms need qualified assessment."], related: [["Haircare", "Back to the category", "/shop/haircare"], ["Panthenol", "Comfort and softness", "/ingredients/panthenol"], ["Search", "A direct route", "/search?q=haircare"]], faqs: [["Will it stop frizz completely?", "No. It is general texture-management guidance, not an absolute promise."], ["Is the catalogue complete?", "No; products appear only after approval."]] },
      { slug: "after-shower-body-routine", title: "After-shower body ritual", subtitle: "RITUAL · AFTER SHOWER", summary: "A simple daily habit beginning with texture and focusing on areas that need extra comfort.", signals: ["Dry feel after showering", "A preference for non-sticky texture", "A personal habit or gift idea"], chapters: [["01 · Choose the texture", "Light for practical days or richer for moments of comfort."], ["02 · Focus on drier areas", "Hands, elbows and legs may need clearer attention."], ["03 · One complementary touch", "Add it only for comfort or a quiet scent."], ["04 · A set when relevant", "Turn the ritual into a gift only when the occasion is clear."]], watchouts: ["Test individual fit on a small area.", "Rich texture does not suit every moment.", "Packaging and shipping need separate approval."], related: [["Bodycare", "Back to the category", "/shop/bodycare"], ["Shea butter", "Understand richer texture", "/ingredients/shea-butter"], ["Gifts and sets", "The gifting route", "/shop/beauty-sets"]], faqs: [["Is this for daily use?", "Adapt it to your need and climate."], ["Can it become a gift?", "Yes, after the set, packaging and operations are approved."]] },
    ],
    ingredient: [
      { slug: "niacinamide", title: "Niacinamide", subtitle: "INGREDIENT · BALANCE", summary: "An ingredient read inside a balanced ritual and suitable texture, never as one answer to every need.", signals: ["A simpler ritual", "Visible balance", "One clear daily step"], chapters: [["Role", "It may support rituals focused on visible balance and general comfort."], ["Fit", "It is understood better through a clear texture and moment of use."], ["Place", "Begin with one step and observe individual response."]], watchouts: ["It is not an absolute treatment.", "The name alone cannot judge a formula.", "Gradual introduction matters more than stacking ingredients."], related: [["Uneven tone", "Concern context", "/concerns/pigmentation"], ["Morning ritual", "Order of use", "/routines/morning-routine-oily-skin"], ["Skincare", "Back to category", "/shop/skincare"]], faqs: [["When is it a useful starting point?", "When you want a simpler ritual and to understand role before product."], ["Does it replace professional advice?", "No; this content is general and does not diagnose or treat."]] },
      { slug: "vitamin-c", title: "Vitamin C", subtitle: "INGREDIENT · MORNING RADIANCE", summary: "Understood inside a clearer morning ritual of texture, timing and protection, without treatment promises.", signals: ["Morning radiance intent", "A lighter daytime texture", "Connection to daily protection"], chapters: [["Role", "It may support routes focused on a more radiant appearance."], ["Timing", "It is often read inside a simple morning ritual."], ["Context", "Daily protection belongs in the complete picture."]], watchouts: ["It is not presented as treatment for pigmentation.", "Formula and texture matter more than name alone.", "Introduce gradually when suitable."], related: [["Uneven tone", "Concern context", "/concerns/pigmentation"], ["Morning ritual", "Order of use", "/routines/morning-routine-oily-skin"], ["Beauty journal", "Read more", "/journal"]], faqs: [["Why connect it to morning?", "This route explains a common context, not an absolute medical rule."], ["Is a result guaranteed?", "No; response varies and no outcome is promised here."]] },
      { slug: "hyaluronic-acid", title: "Hyaluronic acid", subtitle: "INGREDIENT · COMFORT AND TEXTURE", summary: "Read through comfort, texture and integration across skincare or makeup.", signals: ["Texture comfort", "Easy layering", "A bridge between care and base"], chapters: [["Role", "It often appears in contexts connected to hydration and comfort."], ["Texture", "Judge the complete formula, not the ingredient name."], ["Integration", "Observe compatibility with the rest of the layers."]], watchouts: ["It is not proof of product quality on its own.", "Application varies by formula.", "Do not add layers without a clear need."], related: [["Makeup longevity", "Base context", "/concerns/makeup-longwear"], ["Occasion ritual", "Order the layers", "/routines/occasion-base-routine"], ["Makeup", "Back to category", "/shop/makeup"]], faqs: [["Is it only for skincare?", "No; it may appear in makeup contexts depending on formula."], ["Does the name define texture?", "No. Texture comes from the complete formula."]] },
      { slug: "panthenol", title: "Panthenol", subtitle: "INGREDIENT · CALM AND SOFTNESS", summary: "A route to understanding comfort and softness in haircare without universal scalp or hair promises.", signals: ["Post-wash comfort", "Softer ends", "A lighter hair ritual"], chapters: [["Role", "It may support a comfortable, softer feel across different formulas."], ["Place", "Decide whether the question begins at scalp or ends."], ["Texture", "Choose what does not burden your hair in use."]], watchouts: ["It is not one answer to all hair concerns.", "Context and formula determine fit.", "Persistent scalp symptoms need qualified advice."], related: [["Post-wash frizz ritual", "Order after washing", "/routines/humidity-proof-hair-routine"], ["Haircare", "Back to category", "/shop/haircare"], ["Search", "Direct exploration", "/search?q=panthenol"]], faqs: [["When should I begin here?", "When your question is comfort or softness and you want role before product."], ["Does it treat the scalp?", "We make no such claim; persistent symptoms need appropriate assessment."]] },
      { slug: "shea-butter", title: "Shea butter", subtitle: "INGREDIENT · RICHER COMFORT", summary: "A richer texture read inside bodycare or gifting according to climate and moment, never as one answer for everyone.", signals: ["After-shower comfort", "A richer texture", "Daily care or gifting"], chapters: [["Role", "It commonly appears in richer, comfort-led formulas."], ["Moment", "It may suit drier areas or particular moments."], ["Gifting", "It supports a set when the intended use is clear."]], watchouts: ["Rich texture does not suit every moment.", "Do not reduce all bodycare to one ingredient.", "Test individual fit gradually."], related: [["After-shower ritual", "Order of use", "/routines/after-shower-body-routine"], ["Bodycare", "Back to category", "/shop/bodycare"], ["Gifts", "The set route", "/shop/beauty-sets"]], faqs: [["Does it suit summer?", "That depends on the complete texture, time of use and preference."], ["Does it treat dryness?", "We make no treatment claim; this explains texture and context only."]] },
    ],
  },
};

export function getDiscoveryRecord(locale: Locale, kind: DiscoveryKind, slug: string) {
  return discoveryRecords[locale][kind].find((record) => record.slug === slug);
}

export function getDiscoveryKindFromPath(path: string): DiscoveryKind | null {
  const entry = Object.entries(discoveryPaths).find(([, value]) => value === path);
  return (entry?.[0] as DiscoveryKind | undefined) ?? null;
}
