export const journalSlugs = [
  "morning-ritual-for-hot-weather",
  "uneven-tone-without-overcomplication",
  "makeup-longevity-without-heavy-layers",
  "post-wash-hair-rhythm-in-humidity",
  "after-shower-bodycare-by-texture",
  "read-an-ingredient-before-you-choose",
] as const;

export type JournalSlug = (typeof journalSlugs)[number];

export const legacyJournalRedirects: Record<string, string> = {
  "practical-morning-routine-glow-sunscreen-fast-layering": "/journal/morning-ritual-for-hot-weather",
  "pigmentation-routine-feels-random-what-to-fix-first": "/journal/uneven-tone-without-overcomplication",
  "how-to-choose-makeup-longwear-without-heavy-layering": "/journal/makeup-longevity-without-heavy-layers",
  "calm-hair-after-washing-humid-days-without-heavy-layers": "/journal/post-wash-hair-rhythm-in-humidity",
  "after-shower-body-routine-that-is-easy-to-keep": "/journal/after-shower-bodycare-by-texture",
  "niacinamide-explained-plain-language": "/ingredients/niacinamide",
};

export const legacyJournalSlugs = [
  "serum-or-moisturizer-how-to-choose-right-morning-layer",
  "best-light-sunscreen-oily-skin-saudi-weather",
  "build-balanced-morning-routine-combination-skin",
  "niacinamide-explained-plain-language",
  "niacinamide-vs-vitamin-c-which-fits-your-routine",
  "how-to-choose-foundation-finish-for-events",
  "pigmentation-routine-feels-random-what-to-fix-first",
  "practical-morning-routine-glow-sunscreen-fast-layering",
  "heat-dryness-long-days-how-to-keep-makeup-comfortable",
  "travel-ready-beauty-set-what-to-pack-without-overpacking",
  "calm-hair-after-washing-humid-days-without-heavy-layers",
  "after-shower-body-routine-that-is-easy-to-keep",
  "calm-sensitive-skin-routine-without-too-many-steps",
  "vitamin-c-morning-routine-who-benefits-and-when-to-slow-down",
  "when-beauty-set-is-smarter-than-buying-one-by-one",
  "gift-guide-beauty-products-that-still-feel-thoughtful",
  "simple-evening-reset-when-skin-feels-dry-and-tired",
  "how-to-choose-makeup-longwear-without-heavy-layering",
  "hyaluronic-acid-hot-dry-days-what-users-misunderstand-first",
  "first-time-beauty-sets-where-to-start-without-overbuying",
  "pigmentation-routine-after-30-days-what-to-keep-what-to-change",
  "makeup-longwear-workdays-vs-occasions-where-choice-changes",
  "niacinamide-and-hyaluronic-acid-together-when-pairing-helps-and-when-it-confuses",
  "giftable-beauty-sets-by-budget-practical-guide-without-overbuying",
  "sensitive-skin-weather-shifts-what-to-keep-stable-first",
  "hydration-layering-between-ac-and-outdoor-heat-without-heaviness",
  "bundle-or-single-products-after-first-purchase-which-is-smarter",
  "checkout-confirmation-control-after-payment-option-toggle-without-reopening-decision-loop",
  "delivery-commitment-confidence-handoff-from-pdp-context-when-one-hesitation-remains",
  "haircare-second-window-drift-check-after-stability-confirmation",
  "repeat-order-volume-controls-when-refill-urgency-is-high-but-usage-variance-remains",
  "checkout-recovery-after-coupon-rejection-without-restarting-offer-loop",
  "payment-step-confidence-handoff-from-pdp-context-to-cart-execution",
  "post-keep-decision-haircare-rebound-stability-check-next-humidity-window",
  "refill-urgency-controls-when-post-travel-rhythm-is-nearly-stable",
  "coupon-distraction-check-before-final-checkout-confirmation",
  "delivery-window-trust-handoff-from-pdp-to-cart-with-one-hesitation",
  "keep-versus-replace-after-two-humidity-rebound-cycles",
  "repeat-order-timing-guardrails-during-post-travel-rhythm-reset",
  "checkout-objection-compression-before-payment-method-switch-loop",
  "pdp-to-cart-trust-proof-handoff-when-shipping-hesitation-remains",
  "haircare-maintenance-versus-replacement-after-partial-recovery-and-humidity-rebound",
  "repeat-order-confidence-after-travel-week-usage-drift",
  "checkout-side-objection-compression-after-cart-readiness-verification",
  "pdp-to-cart-handoff-prompt-without-category-fallback-loop",
  "haircare-maintenance-versus-replacement-after-replacement-trial-entry",
  "repeat-order-confidence-prompt-with-high-intent-and-partial-usage-consistency",
  "post-article-objection-closure-before-direct-cart-continuation",
  "pdp-proof-snippet-or-full-comparison-when-one-hesitation-remains",
  "haircare-maintenance-threshold-after-simplification-success-before-replacement",
  "reorder-confirmation-prompt-after-first-high-intent-objection-resolution",
  "keep-versus-introduce-when-routine-stability-is-high-but-one-micro-gap-remains",
  "touch-up-path-or-full-base-restart-longwear-reassurance-before-checkout",
  "stable-week-post-friction-simplification-or-haircare-replacement-decision",
  "high-intent-journal-to-pdp-to-cart-progression-with-one-unresolved-objection",
  "two-stable-cycles-or-just-one-when-reorder-confidence-is-really-earned",
  "finish-mismatch-or-durability-limit-how-to-triage-longwear-failure-before-switch",
  "weather-stable-but-friction-high-keep-adjusting-routine-or-change-haircare-product",
  "journal-to-checkout-bridge-when-you-are-product-leaning-but-still-hesitating",
  "post-upgrade-proof-or-full-reorder-when-to-commit-after-a-trial-cycle",
  "longwear-breakdown-sweat-sebum-or-application-drift-before-you-switch-base",
  "after-weather-adjustment-keep-tuning-or-confirm-haircare-product-mismatch",
  "high-intent-path-go-direct-pdp-or-revisit-category-after-journal-decision",
  "reorder-or-upgrade-when-repeat-cycles-feel-stable-but-confidence-drops",
  "long-day-longwear-objection-which-proof-matters-before-pdp-commitment",
  "routine-drift-or-product-mismatch-assign-responsibility-before-switching-haircare",
  "journal-decision-to-category-or-pdp-choose-next-click-without-open-browsing",
  "short-cycle-fluctuation-or-real-decline-before-you-switch-skincare",
  "single-restock-or-set-return-when-value-signals-conflict-with-routine-simplicity",
  "base-finish-or-longwear-which-question-should-hit-the-pdp-first",
  "humidity-shift-or-fit-problem-before-haircare-collection-handoff",
  "season-shift-or-routine-drift-which-explains-mixed-proof-before-switching-skincare",
  "restock-now-or-return-to-a-set-when-low-stock-cues-feel-confusing",
  "finish-or-coverage-doubt-before-opening-a-makeup-pdp",
  "weather-effect-or-product-fit-haircare-bridge-before-you-switch",
  "keep-the-product-or-reset-the-routine-when-results-slip-without-collapsing",
  "reorder-timing-when-bodycare-cadence-changes-between-weeks-and-seasons",
  "is-this-haircare-question-about-weather-recovery-or-true-product-mismatch",
  "after-you-pick-the-collection-which-finish-or-texture-doubt-belongs-to-the-pdp",
  "when-mixed-second-cycle-proof-points-back-to-the-routine",
  "repeat-order-guardrails-when-depletion-cues-are-not-consistent",
  "is-your-hyaluronic-acid-search-about-layering-timing-or-category-fit",
  "when-the-collection-is-settled-what-should-the-pdp-answer-before-checkout",
  "compare-second-cycle-signals-before-switching-a-skincare-product",
  "depletion-versus-upgrade-before-you-repeat-a-bodycare-order",
  "is-your-niacinamide-search-really-about-pigmentation-or-routine-stability",
  "after-a-journal-answer-when-do-you-open-the-collection-and-when-the-pdp",
  "when-a-second-cycle-feels-weaker-before-you-blame-the-product",
  "restock-timing-before-a-bodycare-routine-breaks-from-depletion",
  "does-makeup-longwear-always-mean-a-heavier-base",
  "after-a-niacinamide-answer-should-you-open-the-category-or-the-product",
  "post-conversion-proof-what-confirms-a-skincare-product-earned-a-second-cycle",
  "replenishment-versus-bundle-return-on-repeat-visits",
  "when-a-hyaluronic-acid-search-is-really-about-layering-comfort",
  "from-a-journal-answer-to-a-routine-choice-before-checkout",
  "commercial-proof-before-upgrading-good-enough-skincare-routine",
  "from-pigmentation-question-to-product-confidence-without-overpromising",
  "what-should-be-clear-before-you-open-beauty-sets-again",
  "when-an-extra-haircare-step-earns-its-place-through-repeat-use",
  "proof-before-switching-a-skincare-routine-that-almost-works",
  "resolve-the-objection-before-restarting-base-makeup",
  "enter-beauty-sets-with-a-clear-next-step-not-open-ended-browsing",
  "repeat-use-logic-before-adding-more-to-bodycare",
  "repeat-purchase-confidence-after-a-successful-set-or-routine",
  "makeup-proof-and-objection-handling-for-day-to-evening-transitions",
  "haircare-fit-notes-that-reduce-hesitation-before-collection-visits",
  "bodycare-continuity-that-strengthens-repeat-behavior-without-overbuying",
  "occasion-touch-up-versus-full-redo-before-evening-plans",
  "gift-set-fit-by-scenario-not-by-generic-label",
  "haircare-continuity-after-travel-or-weather-disruption",
  "bodycare-recovery-when-routine-becomes-too-intermittent",
  "hydration-balance-reset-between-ac-and-outdoor-heat",
  "concern-recovery-after-over-layering-what-to-pause-first",
  "replenishment-timing-single-rebuy-vs-returning-to-a-set",
  "fast-morning-recovery-after-a-disrupted-evening-routine",
  "sunscreen-reapplication-over-makeup-without-patchiness",
  "routine-recovery-after-travel-and-busy-weeks",
  "brush-and-sponge-hygiene-cadence-without-overcomplication",
  "evening-reset-after-late-makeup-removal-next-day-comfort",
  "post-purchase-routine-retention-how-to-stay-consistent-after-week-two",
] as const;

const legacySet = new Set<string>(legacyJournalSlugs);
const redirectSet = new Set(Object.keys(legacyJournalRedirects));

export const retiredLegacyJournalSlugs = new Set(
  legacyJournalSlugs.filter((slug) => !redirectSet.has(slug)),
);

export function getLegacyJournalRedirect(slug: string) {
  return legacyJournalRedirects[slug] ?? null;
}

export function isRetiredLegacyJournalSlug(slug: string) {
  return legacySet.has(slug) && !redirectSet.has(slug);
}
