import type { Locale } from "@/lib/i18n";

const images = {
  // PLACEHOLDER: shared with the transition scene until a dedicated perfume
  // still-life concept asset exists. Replace before any perfume launch.
  perfumes: "/elore-assets/transition-burgundy-satin-concept-1672w.avif",
  skincare: "/elore-assets/texture-skincare-serum-concept-1536w.avif",
  makeup: "/elore-assets/texture-makeup-pigment-concept-1536w.avif",
  haircare: "/elore-assets/haircare-ribbon-editorial-concept-1122x1402.avif",
  bodycare: "/elore-assets/bodycare-stone-ritual-concept-1122x1402.avif",
  tools: "/elore-assets/tools-brass-flatlay-concept-1254x1254.avif",
  editorial: "/elore-assets/editorial-skin-light-concept-1122w.avif",
  silk: "/elore-assets/hero-silk-champagne-concept-1672w.avif",
  gifting: "/elore-assets/gifting-folds-concept-1536x1024.avif",
} as const;

export const shopCopy = {
  ar: {
    metadata: {
      title: "المتجر",
      description: "تصفحي عالم ÉLORÉ PARIS عبر فئات العناية والمكياج والهدايا في تجربة هادئة وواضحة.",
      pageName: "متجر ÉLORÉ PARIS",
      pageDescription: "بوابة تسوق تجمع فئات العناية والجمال في مسارات واضحة.",
      home: "الرئيسية",
      shop: "المتجر",
    },
    hero: {
      aria: "مقدمة متجر إلوري باريس",
      eyebrow: "THE ÉLORÉ EDIT",
      title: "الجمال، باختيار\nأكثر هدوءًا.",
      body: "ابدئي من الفئة التي تهمك، أو ابحثي مباشرة عمّا تعرفينه. هنا تظهر المنتجات فقط بعد اعتماد بياناتها وصورها.",
      primary: "تصفحي الأقسام",
      secondary: "ابحثي بالاسم",
      image: images.silk,
      imageAlt: "تكوين تحريري من الحرير بلون الشمبانيا",
      conceptNotice: "صورة مفاهيمية — لا تمثل منتجًا معروضًا للبيع.",
    },
    categories: {
      aria: "تصنيفات المتجر",
      eyebrow: "SHOP BY CATEGORY",
      title: "أبواب واضحة.\nواختيار أقرب لك.",
      body: "تصفحي الفئات، ثم انتقلي إلى القسم الذي يناسب ما تبحثين عنه.",
    },
    catalog: {
      aria: "المنتجات المعتمدة",
      eyebrow: "APPROVED CATALOGUE",
      availableTitle: "اختيارات متاحة الآن",
      availableBody: "هذه هي المنتجات المنشورة حاليًا ببياناتها وصورها المعتمدة.",
      emptyTitle: "نجهّز الرف بعناية.",
      emptyBody: "لا توجد منتجات منشورة الآن. إلى أن يكتمل الاعتماد، يمكنك استكشاف الفئات ودليل الجمال دون وعود أو أسعار غير معتمدة.",
      productCta: "عرض التفاصيل",
      emptyPrimary: "اقرئي دليل الجمال",
      emptySecondary: "الثقة والسياسات",
      count: (count: number) => `عدد المنتجات المنشورة: ${count}`,
    },
    editorial: {
      aria: "طرق تساعدك على الاختيار",
      eyebrow: "CHOOSE WITH INTENT",
      title: "لا تعرفين من أين\nتبدئين؟",
      body: "ابدئي من احتياج، أو روتين، أو مكوّن. هذه المسارات تساعدك على تضييق الاختيار قبل الوصول إلى المنتج.",
      image: images.editorial,
      imageAlt: "دراسة تحريرية مفاهيمية للضوء على البشرة",
      conceptNotice: "صورة تحريرية مفاهيمية.",
      cta: "استكشفي دليل الجمال",
    },
    collections: [
      ["العطور", "PERFUMES", "/shop/perfumes", images.perfumes, "shop_hub_collection_perfumes"],
      ["العناية بالبشرة", "SKINCARE", "/shop/skincare", images.skincare, "shop_hub_collection_skincare"],
      ["المكياج", "MAKEUP", "/shop/makeup", images.makeup, "shop_hub_collection_makeup"],
      ["العناية بالشعر", "HAIRCARE", "/shop/haircare", images.haircare, "shop_hub_collection_haircare"],
      ["العناية بالجسم", "BODYCARE", "/shop/bodycare", images.bodycare, "shop_hub_collection_bodycare"],
      ["الأدوات", "TOOLS", "/shop/tools", images.tools, "shop_hub_collection_tools"],
      ["مجموعات الجمال", "BEAUTY SETS", "/shop/beauty-sets", images.gifting, "shop_hub_collection_beauty_sets"],
    ],
    routes: [
      ["01", "حسب الاحتياج", "ابدئي بالنتيجة التي تبحثين عنها.", "/concerns", "shop_hub_to_concerns"],
      ["02", "حسب الروتين", "رتّبي الخطوات قبل اختيار المنتجات.", "/routines", "shop_hub_to_routines"],
      ["03", "حسب المكوّن", "افهمي التركيبة وما يناسب احتياجك.", "/ingredients", "shop_hub_to_ingredients"],
      ["04", "بحث مباشر", "عندما تعرفين الاسم أو الفئة.", "/search", "shop_hub_to_search"],
    ],
    imageAlt: (title: string) => `صورة مفاهيمية لقسم ${title}`,
  },
  en: {
    metadata: {
      title: "Shop",
      description: "Explore the ÉLORÉ PARIS world through care, makeup and gifting in a quieter, clearer experience.",
      pageName: "ÉLORÉ PARIS shop",
      pageDescription: "A considered gateway to beauty and care categories.",
      home: "Home",
      shop: "Shop",
    },
    hero: {
      aria: "ÉLORÉ PARIS shop introduction",
      eyebrow: "THE ÉLORÉ EDIT",
      title: "Beauty, chosen\nwith more clarity.",
      body: "Begin with the category that matters to you, or search directly for what you know. Products appear here only after their data and imagery are approved.",
      primary: "Browse categories",
      secondary: "Search by name",
      image: images.silk,
      imageAlt: "Editorial composition of champagne-toned silk",
      conceptNotice: "Concept image — not a product offered for sale.",
    },
    categories: {
      aria: "Shop categories",
      eyebrow: "SHOP BY CATEGORY",
      title: "Clear doors.\nA closer choice.",
      body: "Browse the categories, then enter the section that best matches what you are looking for.",
    },
    catalog: {
      aria: "Approved products",
      eyebrow: "APPROVED CATALOGUE",
      availableTitle: "Available now",
      availableBody: "These are the products currently published with approved data and imagery.",
      emptyTitle: "We are composing the shelf.",
      emptyBody: "No products are published yet. Until approval is complete, explore the categories and beauty journal without unverified prices or promises.",
      productCta: "View details",
      emptyPrimary: "Read the beauty journal",
      emptySecondary: "Trust and policies",
      count: (count: number) => `${count} ${count === 1 ? "product" : "products"} published`,
    },
    editorial: {
      aria: "Ways to choose",
      eyebrow: "CHOOSE WITH INTENT",
      title: "Not sure where\nto begin?",
      body: "Start with a concern, ritual or ingredient. These routes help narrow the choice before you arrive at a product.",
      image: images.editorial,
      imageAlt: "Concept editorial study of light on skin",
      conceptNotice: "Concept editorial image.",
      cta: "Explore the beauty journal",
    },
    collections: [
      ["Perfumes", "PERFUMES", "/shop/perfumes", images.perfumes, "shop_hub_collection_perfumes"],
      ["Skincare", "SKINCARE", "/shop/skincare", images.skincare, "shop_hub_collection_skincare"],
      ["Makeup", "MAKEUP", "/shop/makeup", images.makeup, "shop_hub_collection_makeup"],
      ["Haircare", "HAIRCARE", "/shop/haircare", images.haircare, "shop_hub_collection_haircare"],
      ["Bodycare", "BODYCARE", "/shop/bodycare", images.bodycare, "shop_hub_collection_bodycare"],
      ["Tools", "TOOLS", "/shop/tools", images.tools, "shop_hub_collection_tools"],
      ["Beauty sets", "BEAUTY SETS", "/shop/beauty-sets", images.gifting, "shop_hub_collection_beauty_sets"],
    ],
    routes: [
      ["01", "By concern", "Begin with the result you are looking for.", "/concerns", "shop_hub_to_concerns"],
      ["02", "By ritual", "Arrange the steps before choosing products.", "/routines", "shop_hub_to_routines"],
      ["03", "By ingredient", "Understand the formula and what suits you.", "/ingredients", "shop_hub_to_ingredients"],
      ["04", "Direct search", "When you know the name or category.", "/search", "shop_hub_to_search"],
    ],
    imageAlt: (title: string) => `Concept image for ${title}`,
  },
} satisfies Record<Locale, unknown>;
