import type { Locale } from "./i18n";

export type TrustSlug = "verification" | "privacy" | "shipping" | "returns" | "authenticity";
export type SupportSlug = "about" | "contact" | "faq" | "terms";

export type ContentSection = {
  title: string;
  body: string;
  points?: string[];
};

export type TrustSupportRecord = {
  slug: TrustSlug | SupportSlug;
  eyebrow: string;
  title: string;
  summary: string;
  status: string;
  sections: ContentSection[];
  faqs: Array<[string, string]>;
};

export const trustSlugs: TrustSlug[] = ["verification", "privacy", "shipping", "returns", "authenticity"];
export const supportSlugs: SupportSlug[] = ["about", "contact", "faq", "terms"];

const provisional = {
  ar: "نسخة معلوماتية مؤقتة — لا تُعد وعدًا تجاريًا أو نصًا قانونيًا نهائيًا.",
  en: "Provisional information — not a final commercial promise or legal notice.",
} as const;

export const trustContent: Record<Locale, Record<TrustSlug, TrustSupportRecord>> = {
  ar: {
    verification: { slug: "verification", eyebrow: "BUSINESS CLARITY", title: "بيانات المنشأة،\nبوضوح.", summary: "سيظهر هنا الاسم القانوني والسجل والرقم الضريبي ووسائل التواصل الرسمية بعد اعتمادها من مالك النشاط.", status: provisional.ar, sections: [{ title: "ما سنعرضه", body: "هوية الجهة البائعة وبيانات التسجيل والفوترة ووسيلة اتصال موثقة.", points: ["الاسم القانوني كما هو مسجل", "السجل والرقم الضريبي عند انطباقهما", "عنوان وقناة دعم معتمدان"] }, { title: "ما لن نفترضه", body: "لن نضع أرقامًا أو عناوين أو صفات قانونية غير موثقة، ولن نحول بيانات النموذج الأولي إلى حقيقة منشورة." }], faqs: [["لماذا لا تظهر البيانات الآن؟", "لأن مصدرًا رسميًا قابلًا للمراجعة لم يُسلّم بعد."], ["هل المتجر مفتوح للبيع؟", "لا. الشراء والفهرسة العامة يظلان محجوبين حتى اكتمال الاعتمادات."]] },
    privacy: { slug: "privacy", eyebrow: "PRIVACY", title: "خصوصيتك،\nدون غموض.", summary: "نوضح البيانات المطلوبة والغرض منها ومدة الاحتفاظ بها، بعد اعتماد البنية القانونية ومزودي الخدمة.", status: provisional.ar, sections: [{ title: "المبدأ", body: "جمع أقل قدر ضروري من البيانات، واستخدامه للغرض المعلن فقط، مع ضوابط وصول ومراجعة." }, { title: "قبل النشر", body: "يجب توثيق مزودي الدفع والشحن والتحليلات والاستضافة، ومسارات طلب الوصول أو التصحيح أو الحذف.", points: ["سجل واضح لأغراض المعالجة", "قائمة موثقة بالجهات المعالجة", "مدة احتفاظ ومسار طلب حقوق واضحان"] }], faqs: [["هل تستخدمون بيانات دفع حقيقية الآن؟", "لا توجد تجارة عامة مفعلة في النسخة الحالية."], ["كيف أطلب حذف بياناتي؟", "ستُنشر القناة الرسمية بعد اعتماد مسؤول الخصوصية ووسيلة التواصل."]] },
    shipping: { slug: "shipping", eyebrow: "DELIVERY", title: "شحن يمكن\nفهمه قبل الدفع.", summary: "المناطق والرسوم والمدة تبدأ من عقد مزود الشحن وبيانات تشغيلية حقيقية، لا من تقديرات تسويقية.", status: provisional.ar, sections: [{ title: "ما سيظهر عند الاعتماد", body: "المدن المدعومة والرسوم وموعد تجهيز الطلب ونافذة التسليم وآلية التتبع." }, { title: "الاستثناءات", body: "تُوضح تأخيرات المواسم والعناوين غير المكتملة والمنتجات المقيدة إن وجدت قبل تأكيد الطلب." }], faqs: [["كم يستغرق التوصيل؟", "لم تُعتمد نافذة تسليم نهائية بعد."], ["هل الشحن متاح لكل المملكة؟", "ستُحدد التغطية من بيانات مزود الشحن المعتمد."]] },
    returns: { slug: "returns", eyebrow: "RETURNS", title: "قرار واضح،\nحتى بعد الاستلام.", summary: "ستشرح السياسة شروط الإرجاع والاستبدال والاسترداد بعبارات قابلة للتنفيذ ومتوافقة مع طبيعة مستحضرات التجميل.", status: provisional.ar, sections: [{ title: "ما يحتاج اعتمادًا", body: "مدة الطلب وحالة العبوة والاستثناءات الصحية وآلية فحص المنتج ورسوم الإرجاع." }, { title: "مسار عادل", body: "رقم طلب، سبب واضح، مراجعة موثقة، ثم نتيجة ومدة استرداد معلنة دون وعود غير قابلة للتحقق." }], faqs: [["هل يمكن إرجاع منتج مفتوح؟", "لم تُعتمد الاستثناءات الصحية والقانونية النهائية بعد."], ["متى يصل المبلغ؟", "تتحدد المدة بعد ربط وسيلة الدفع واعتماد قواعد الاسترداد."]] },
    authenticity: { slug: "authenticity", eyebrow: "PRODUCT PROVENANCE", title: "الأصالة تبدأ\nمن سجل قابل للمراجعة.", summary: "لا نستخدم كلمة أصلي كعبارة دعائية؛ يجب أن تسندها سلسلة توريد وملصق ومصدر وفاتورة يمكن التحقق منها.", status: provisional.ar, sections: [{ title: "أدلة المنتج", body: "مصدر التوريد وبيانات المستورد أو الموزع والدفعة والملصق والامتثال عند انطباقه." }, { title: "ادعاءات منضبطة", body: "لا تُنشر نتائج أو نسب أو وعود تجميلية قبل وجود مصدر ومراجعة واضحة." }], faqs: [["كيف أتحقق من منتج؟", "ستُضاف آلية تحقق مرتبطة بالدفعة بعد اعتماد بيانات الكتالوج والتوريد."], ["هل الصور الحالية صور منتجات؟", "لا. الصور المفاهيمية موسومة ولا تمثل عبوة معتمدة للبيع."]] },
  },
  en: {
    verification: { slug: "verification", eyebrow: "BUSINESS CLARITY", title: "Business details,\nmade clear.", summary: "The legal name, registration, tax details and official contact channel will appear only after owner verification.", status: provisional.en, sections: [{ title: "What we will publish", body: "The selling entity, registration and invoicing details, and a verified contact route.", points: ["Registered legal name", "Registration and tax identifiers where applicable", "Approved address and support channel"] }, { title: "What we will not infer", body: "We will not publish invented identifiers, addresses or legal status, or treat prototype data as business truth." }], faqs: [["Why are the details not visible yet?", "No reviewable official source has been supplied."], ["Is the store open for sales?", "No. Public commerce and indexing remain gated until approvals are complete."]] },
    privacy: { slug: "privacy", eyebrow: "PRIVACY", title: "Privacy,\nwithout ambiguity.", summary: "We will explain what data is needed, why it is used and how long it is kept after the legal and provider model is approved.", status: provisional.en, sections: [{ title: "The principle", body: "Collect only what is necessary, use it for the disclosed purpose, and control and review access." }, { title: "Before publication", body: "Payment, shipping, analytics and hosting processors plus access, correction and deletion routes must be documented.", points: ["Clear processing purposes", "Verified processor inventory", "Retention periods and rights request route"] }], faqs: [["Do you process live payment data now?", "Public commerce is not enabled in this build."], ["How can I request deletion?", "The official route will be published after the privacy owner and contact channel are approved."]] },
    shipping: { slug: "shipping", eyebrow: "DELIVERY", title: "Delivery you can\nunderstand before paying.", summary: "Coverage, fees and timing must come from a real carrier contract and operating data, not marketing estimates.", status: provisional.en, sections: [{ title: "What approval will add", body: "Supported locations, fees, fulfilment timing, delivery windows and tracking steps." }, { title: "Exceptions", body: "Seasonal delays, incomplete addresses and any restricted products will be explained before order confirmation." }], faqs: [["How long does delivery take?", "No final delivery window has been approved."], ["Is delivery available across Saudi Arabia?", "Coverage will be derived from the approved carrier data."]] },
    returns: { slug: "returns", eyebrow: "RETURNS", title: "A clear decision,\neven after delivery.", summary: "The policy will explain return, exchange and refund conditions in enforceable language suited to cosmetics.", status: provisional.en, sections: [{ title: "What needs approval", body: "Request window, packaging condition, hygiene exceptions, inspection method and return fees." }, { title: "A fair route", body: "Order reference, clear reason, documented review, then an explained outcome and refund timing." }], faqs: [["Can an opened product be returned?", "Final hygiene and legal exceptions have not been approved."], ["When will the refund arrive?", "Timing depends on the approved payment integration and refund rules."]] },
    authenticity: { slug: "authenticity", eyebrow: "PRODUCT PROVENANCE", title: "Authenticity begins\nwith a reviewable record.", summary: "Authentic is not a decorative claim; it requires a traceable supplier, label, source and invoice.", status: provisional.en, sections: [{ title: "Product evidence", body: "Supplier provenance, importer or distributor, batch, label and applicable compliance records." }, { title: "Disciplined claims", body: "No result, percentage or beauty promise is published without a source and explicit review." }], faqs: [["How will I verify a product?", "A batch-linked method will follow catalog and supplier approval."], ["Are the current images product photographs?", "No. Concept imagery is labelled and does not represent an approved item for sale."]] },
  },
};

export const supportContent: Record<Locale, Record<SupportSlug, TrustSupportRecord>> = {
  ar: {
    about: { slug: "about", eyebrow: "ABOUT ÉLORÉ", title: "جمال باختيار\nمدروس.", summary: "تصور لبيت جمال رقمي يجمع الحس الباريسي مع وضوح يناسب الحياة في السعودية. قصة العلامة النهائية تنتظر اعتماد المالك.", status: provisional.ar, sections: [{ title: "الفكرة", body: "اختيارات أهدأ، معلومات أوضح، وصور أقرب للحقيقة قبل اتخاذ القرار." }, { title: "ما نلتزم به في النموذج", body: "لا كتالوج وهمي، لا ادعاءات بلا مصدر، ولا تحويل للمحتوى المؤقت إلى حقيقة نهائية." }], faqs: [["هل هذه قصة العلامة النهائية؟", "لا. هي صياغة مؤقتة حتى اعتماد النشأة والرؤية من المالك."], ["لمن صُممت التجربة؟", "لجمهور عربي وإنجليزي في السعودية يبحث عن اختيار جمال أوضح وأقل ضجيجًا."]] },
    contact: { slug: "contact", eyebrow: "CONTACT", title: "طريق واضح\nإلى المساعدة.", summary: "قنوات البريد والهاتف وواتساب لم تُعتمد بعد. نعرض فقط المسارات الداخلية العاملة دون اختلاق وسيلة تواصل.", status: provisional.ar, sections: [{ title: "المتاح الآن", body: "يمكن استخدام الأسئلة الشائعة وصفحات السياسات وتتبع الطلب. لا توجد استجابة بشرية أو مدة خدمة معلنة بعد.", points: ["الأسئلة الشائعة", "الثقة والسياسات", "تتبع الطلب التجريبي"] }, { title: "قبل الإطلاق", body: "يلزم اعتماد مالك القناة وساعات العمل وزمن الاستجابة وسياسة التصعيد والخصوصية." }], faqs: [["أين البريد أو رقم الهاتف؟", "لن ننشر قناة غير مؤكدة. تضاف بعد تسليمها والتحقق منها."], ["هل يمكنني تقديم شكوى الآن؟", "لا توجد قناة شكاوى تشغيلية معتمدة في النموذج الحالي."]] },
    faq: { slug: "faq", eyebrow: "FREQUENTLY ASKED", title: "إجابات صريحة،\nحتى عندما تكون معلّقة.", summary: "نوضح ما يعمل الآن وما ينتظر اعتمادًا بدل تقديم وعود عن الدفع أو الشحن أو الإرجاع.", status: provisional.ar, sections: [{ title: "الشراء والدفع", body: "التجارة العامة غير مفعلة، ولا توجد وسيلة دفع أو سعر أو مخزون معتمد للنشر." }, { title: "الشحن والإرجاع", body: "التغطية والرسوم والمدد والاستثناءات تنتظر عقود المزود والسياسة القانونية." }, { title: "المنتجات والمحتوى", body: "الصور المفاهيمية ليست منتجات للبيع، والمحتوى التعليمي لا يبدل استشارة مختص." }], faqs: [["هل أستطيع الشراء الآن؟", "لا. مسار الشراء العام محجوب حتى اكتمال الكتالوج والمزودين والاعتماد."], ["هل الأسعار المعروضة نهائية؟", "لا توجد أسعار عامة معتمدة في هذه المرحلة."], ["هل الروتينات نصيحة طبية؟", "لا. هي معلومات عامة ولا تشخّص أو تعالج حالة."]] },
    terms: { slug: "terms", eyebrow: "TERMS", title: "شروط مفهومة،\nقبل الموافقة.", summary: "هذه ليست شروط بيع نهائية. يلزم اعتماد هوية المنشأة والدفع والشحن والإرجاع والاختصاص القانوني أولًا.", status: provisional.ar, sections: [{ title: "نطاق الاستخدام", body: "يمكن تصفح النموذج لأغراض العرض. لا ينشأ عقد بيع عام لأن التجارة غير مفعلة." }, { title: "المحتوى والملكية", body: "العلامات والأصول المعتمدة تبقى لأصحابها، والصور المفاهيمية موسومة ولا تمثل كتالوجًا." }, { title: "قبل الإطلاق التجاري", body: "تُراجع الأهلية والدفع والإلغاء والتوصيل والإرجاع والمسؤولية والاختصاص وآلية الشكاوى قانونيًا." }], faqs: [["هل هذه الشروط نافذة للبيع؟", "لا. هي هيكل مؤقت ولا يحل محل مراجعة قانونية معتمدة."], ["متى تصبح نهائية؟", "بعد اعتماد بيانات المنشأة والسياسات والمزودين وإصدار نسخة مؤرخة."]] },
  },
  en: {
    about: { slug: "about", eyebrow: "ABOUT ÉLORÉ", title: "Beauty,\nconsidered.", summary: "A concept for a digital beauty house pairing Parisian sensibility with clarity for Saudi life. The final brand story awaits owner approval.", status: provisional.en, sections: [{ title: "The idea", body: "A quieter edit, clearer information and imagery closer to the truth before a decision." }, { title: "What this prototype protects", body: "No invented catalog, unsupported claims or conversion of provisional content into final brand truth." }], faqs: [["Is this the final brand story?", "No. It remains provisional until the origin and vision are owner-approved."], ["Who is the experience for?", "Arabic and English audiences in Saudi Arabia seeking clearer, quieter beauty choices."]] },
    contact: { slug: "contact", eyebrow: "CONTACT", title: "A clear route\nto support.", summary: "Email, phone and WhatsApp are not approved. We show only working internal routes rather than inventing a contact channel.", status: provisional.en, sections: [{ title: "Available now", body: "Use the FAQ, policy pages and order tracking. No human response or service level is currently promised.", points: ["Frequently asked questions", "Trust and policies", "Prototype order tracking"] }, { title: "Before launch", body: "The channel owner, hours, response target, escalation and privacy handling must be approved." }], faqs: [["Where is the email or phone number?", "We will not publish an unverified channel. It will appear after delivery and verification."], ["Can I submit a complaint now?", "There is no approved operational complaint channel in this prototype."]] },
    faq: { slug: "faq", eyebrow: "FREQUENTLY ASKED", title: "Direct answers,\neven when pending.", summary: "We distinguish what works now from what awaits approval instead of promising payment, delivery or returns outcomes.", status: provisional.en, sections: [{ title: "Purchasing and payment", body: "Public commerce is disabled. No public payment method, price or stock record is approved." }, { title: "Shipping and returns", body: "Coverage, fees, timing and exceptions await carrier and legal approval." }, { title: "Products and guidance", body: "Concept imagery is not inventory, and educational content is not professional medical advice." }], faqs: [["Can I purchase now?", "No. Public checkout remains blocked until catalog, providers and approvals are complete."], ["Are displayed prices final?", "There are no approved public prices at this stage."], ["Are routines medical advice?", "No. They are general information and do not diagnose or treat a condition."]] },
    terms: { slug: "terms", eyebrow: "TERMS", title: "Terms you can\nunderstand before agreeing.", summary: "These are not final sales terms. The entity, payment, delivery, returns and governing framework must be approved first.", status: provisional.en, sections: [{ title: "Use of this prototype", body: "The experience can be browsed for demonstration. No public sales contract is formed because commerce is disabled." }, { title: "Content and ownership", body: "Approved marks and assets remain with their owners; labelled concept imagery is not a product catalog." }, { title: "Before commercial launch", body: "Eligibility, payment, cancellation, delivery, returns, liability, governing law and complaints require legal review." }], faqs: [["Are these terms effective for sales?", "No. They are a provisional structure and not a substitute for approved legal review."], ["When will they be final?", "After the entity, policies and providers are approved and a dated version is issued."]] },
  },
};

export const trustHubCopy = {
  ar: { eyebrow: "TRUST DIRECTORY", title: "الثقة ليست\nشارة.", intro: "هي بيانات وسياسات وأدلة يمكن فهمها ومراجعتها قبل أن نطلب منك قرارًا.", directory: "دليل الثقة", principlesTitle: "ما نعرفه.\nوما ينتظر الاعتماد.", closeTitle: "الوضوح قبل\nالتجارة.", open: "افتحي الملف", support: "الأسئلة الشائعة", notice: provisional.ar },
  en: { eyebrow: "TRUST DIRECTORY", title: "Trust is not\na badge.", intro: "It is information, policy and evidence you can understand and review before we ask for a decision.", directory: "Trust directory", principlesTitle: "What we know.\nWhat awaits approval.", closeTitle: "Clarity before\ncommerce.", open: "Open record", support: "Frequently asked questions", notice: provisional.en },
} as const;

export function getTrustRecord(locale: Locale, slug: string) {
  return trustSlugs.includes(slug as TrustSlug) ? trustContent[locale][slug as TrustSlug] : null;
}

export function getSupportRecord(locale: Locale, slug: string) {
  return supportSlugs.includes(slug as SupportSlug) ? supportContent[locale][slug as SupportSlug] : null;
}
