import type { Locale } from "./i18n";

export type TrustSlug = "verification" | "privacy" | "shipping" | "returns" | "authenticity";
export type SupportSlug = "about" | "contact" | "faq" | "terms";

export type ContentSection = {
  title: string;
  body: string;
  points?: string[];
};

export type TrustSupportRecord = {
  slug: TrustSlug | SupportSlug;
  eyebrow: string;
  title: string;
  summary: string;
  status: string;
  sections: ContentSection[];
  faqs: Array<[string, string]>;
};

export const trustSlugs: TrustSlug[] = ["verification", "privacy", "shipping", "returns", "authenticity"];
export const supportSlugs: SupportSlug[] = ["about", "contact", "faq", "terms"];

const provisional = {
  ar: "تُحدّث هذه المعلومات عند اعتماد بيانات التشغيل والسياسات الرسمية.",
  en: "This information is updated as verified operating details and policies are approved.",
} as const;

export const trustContent: Record<Locale, Record<TrustSlug, TrustSupportRecord>> = {
  ar: {
    verification: { slug: "verification", eyebrow: "BUSINESS CLARITY", title: "بيانات المنشأة،\nبوضوح.", summary: "سيظهر هنا الاسم القانوني والسجل والرقم الضريبي ووسائل التواصل الرسمية بعد اعتمادها من مالك النشاط.", status: provisional.ar, sections: [{ title: "ما سنعرضه", body: "هوية الجهة البائعة وبيانات التسجيل والفوترة ووسيلة اتصال موثقة.", points: ["الاسم القانوني كما هو مسجل", "السجل والرقم الضريبي عند انطباقهما", "عنوان وقناة دعم معتمدان"] }, { title: "ما لن نفترضه", body: "لن نضع أرقامًا أو عناوين أو صفات قانونية غير موثقة، ولن نحول بيانات النموذج الأولي إلى حقيقة منشورة." }], faqs: [["لماذا لا تظهر البيانات الآن؟", "لأن مصدرًا رسميًا قابلًا للمراجعة لم يُسلّم بعد."], ["هل المتجر مفتوح للبيع؟", "لا. الشراء والفهرسة العامة يظلان محجوبين حتى اكتمال الاعتمادات."]] },
    privacy: { slug: "privacy", eyebrow: "PRIVACY", title: "خصوصيتك،\nدون غموض.", summary: "نوضح البيانات المطلوبة والغرض منها ومدة الاحتفاظ بها، بعد اعتماد البنية القانونية ومزودي الخدمة.", status: provisional.ar, sections: [{ title: "المبدأ", body: "جمع أقل قدر ضروري من البيانات، واستخدامه للغرض المعلن فقط، مع ضوابط وصول ومراجعة." }, { title: "قبل النشر", body: "يجب توثيق مزودي الدفع والشحن والتحليلات والاستضافة، ومسارات طلب الوصول أو التصحيح أو الحذف.", points: ["سجل واضح لأغراض المعالجة", "قائمة موثقة بالجهات المعالجة", "مدة احتفاظ ومسار طلب حقوق واضحان"] }], faqs: [["هل تستخدمون بيانات دفع حقيقية الآن؟", "لا توجد تجارة عامة مفعلة في النسخة الحالية."], ["كيف أطلب حذف بياناتي؟", "ستُنشر القناة الرسمية بعد اعتماد مسؤول الخصوصية ووسيلة التواصل."]] },
    shipping: { slug: "shipping", eyebrow: "DELIVERY", title: "شحن يمكن\nفهمه قبل الدفع.", summary: "المناطق والرسوم والمدة تبدأ من عقد مزود الشحن وبيانات تشغيلية حقيقية، لا من تقديرات تسويقية.", status: provisional.ar, sections: [{ title: "ما سيظهر عند الاعتماد", body: "المدن المدعومة والرسوم وموعد تجهيز الطلب ونافذة التسليم وآلية التتبع." }, { title: "الاستثناءات", body: "تُوضح تأخيرات المواسم والعناوين غير المكتملة والمنتجات المقيدة إن وجدت قبل تأكيد الطلب." }], faqs: [["كم يستغرق التوصيل؟", "لم تُعتمد نافذة تسليم نهائية بعد."], ["هل الشحن متاح لكل المملكة؟", "ستُحدد التغطية من بيانات مزود الشحن المعتمد."]] },
    returns: { slug: "returns", eyebrow: "RETURNS", title: "قرار واضح،\nحتى بعد الاستلام.", summary: "ستشرح السياسة شروط الإرجاع والاستبدال والاسترداد بعبارات قابلة للتنفيذ ومتوافقة مع طبيعة مستحضرات التجميل.", status: provisional.ar, sections: [{ title: "ما يحتاج اعتمادًا", body: "مدة الطلب وحالة العبوة والاستثناءات الصحية وآلية فحص المنتج ورسوم الإرجاع." }, { title: "مسار عادل", body: "رقم طلب، سبب واضح، مراجعة موثقة، ثم نتيجة ومدة استرداد معلنة دون وعود غير قابلة للتحقق." }], faqs: [["هل يمكن إرجاع منتج مفتوح؟", "لم تُعتمد الاستثناءات الصحية والقانونية النهائية بعد."], ["متى يصل المبلغ؟", "تتحدد المدة بعد ربط وسيلة الدفع واعتماد قواعد الاسترداد."]] },
    authenticity: { slug: "authenticity", eyebrow: "PRODUCT PROVENANCE", title: "الأصالة تبدأ\nمن سجل قابل للمراجعة.", summary: "لا نستخدم كلمة أصلي كعبارة دعائية؛ يجب أن تسندها سلسلة توريد وملصق ومصدر وفاتورة يمكن التحقق منها.", status: provisional.ar, sections: [{ title: "أدلة المنتج", body: "مصدر التوريد وبيانات المستورد أو الموزع والدفعة والملصق والامتثال عند انطباقه." }, { title: "ادعاءات منضبطة", body: "لا تُنشر نتائج أو نسب أو وعود تجميلية قبل وجود مصدر ومراجعة واضحة." }], faqs: [["كيف أتحقق من منتج؟", "ستُضاف آلية تحقق مرتبطة بالدفعة بعد اعتماد بيانات الكتالوج والتوريد."], ["هل الصور الحالية صور منتجات؟", "لا. الصور المفاهيمية موسومة ولا تمثل عبوة معتمدة للبيع."]] },
  },
  en: {
    verification: { slug: "verification", eyebrow: "BUSINESS CLARITY", title: "Business details,\nmade clear.", summary: "The legal name, registration, tax details and official contact channel will appear only after owner verification.", status: provisional.en, sections: [{ title: "What we will publish", body: "The selling entity, registration and invoicing details, and a verified contact route.", points: ["Registered legal name", "Registration and tax identifiers where applicable", "Approved address and support channel"] }, { title: "What we will not infer", body: "We will not publish invented identifiers, addresses or legal status, or treat prototype data as business truth." }], faqs: [["Why are the details not visible yet?", "No reviewable official source has been supplied."], ["Is the store open for sales?", "No. Public commerce and indexing remain gated until approvals are complete."]] },
    privacy: { slug: "privacy", eyebrow: "PRIVACY", title: "Privacy,\nwithout ambiguity.", summary: "We will explain what data is needed, why it is used and how long it is kept after the legal and provider model is approved.", status: provisional.en, sections: [{ title: "The principle", body: "Collect only what is necessary, use it for the disclosed purpose, and control and review access." }, { title: "Before publication", body: "Payment, shipping, analytics and hosting processors plus access, correction and deletion routes must be documented.", points: ["Clear processing purposes", "Verified processor inventory", "Retention periods and rights request route"] }], faqs: [["Do you process live payment data now?", "Public commerce is not enabled in this build."], ["How can I request deletion?", "The official route will be published after the privacy owner and contact channel are approved."]] },
    shipping: { slug: "shipping", eyebrow: "DELIVERY", title: "Delivery you can\nunderstand before paying.", summary: "Coverage, fees and timing must come from a real carrier contract and operating data, not marketing estimates.", status: provisional.en, sections: [{ title: "What approval will add", body: "Supported locations, fees, fulfilment timing, delivery windows and tracking steps." }, { title: "Exceptions", body: "Seasonal delays, incomplete addresses and any restricted products will be explained before order confirmation." }], faqs: [["How long does delivery take?", "No final delivery window has been approved."], ["Is delivery available across Saudi Arabia?", "Coverage will be derived from the approved carrier data."]] },
    returns: { slug: "returns", eyebrow: "RETURNS", title: "A clear decision,\neven after delivery.", summary: "The policy will explain return, exchange and refund conditions in enforceable language suited to cosmetics.", status: provisional.en, sections: [{ title: "What needs approval", body: "Request window, packaging condition, hygiene exceptions, inspection method and return fees." }, { title: "A fair route", body: "Order reference, clear reason, documented review, then an explained outcome and refund timing." }], faqs: [["Can an opened product be returned?", "Final hygiene and legal exceptions have not been approved."], ["When will the refund arrive?", "Timing depends on the approved payment integration and refund rules."]] },
    authenticity: { slug: "authenticity", eyebrow: "PRODUCT PROVENANCE", title: "Authenticity begins\nwith a reviewable record.", summary: "Authentic is not a decorative claim; it requires a traceable supplier, label, source and invoice.", status: provisional.en, sections: [{ title: "Product evidence", body: "Supplier provenance, importer or distributor, batch, label and applicable compliance records." }, { title: "Disciplined claims", body: "No result, percentage or beauty promise is published without a source and explicit review." }], faqs: [["How will I verify a product?", "A batch-linked method will follow catalog and supplier approval."], ["Are the current images product photographs?", "No. Concept imagery is labelled and does not represent an approved item for sale."]] },
  },
};

export const supportContent: Record<Locale, Record<SupportSlug, TrustSupportRecord>> = {
  ar: {
    about: { slug: "about", eyebrow: "ABOUT ÉLORÉ", title: "جمال يُصاغ بنية.\nويُروى كتجربة.", summary: "بيت جمال رقمي يجمع حسًا تحريريًا راقيًا مع وضوح يناسب إيقاع الحياة في السعودية؛ لتصبح المعرفة جزءًا طبيعيًا من كل اختيار.", status: "قصتنا تتطور مع المجموعة، لكن مبدأنا ثابت: الجمال يبدأ من الوضوح.", sections: [{ title: "الفكرة", body: "اختيارات أهدأ، معلومات أوضح، وصور تحترم الحقيقة قبل اتخاذ القرار." }, { title: "ما نلتزم به", body: "لا مبالغة في الوعود، ولا منتج بلا بيانات موثقة، ولا محتوى يسبق الحقيقة التي يستند إليها." }], faqs: [["ما الذي يميز ÉLORÉ؟", "تجربة عربية وإنجليزية تربط الجمال بالمعرفة، وتمنح كل قرار مساحة أهدأ وأكثر وضوحًا."], ["لمن صُممت التجربة؟", "لجمهور في السعودية يبحث عن اختيار جمال راقٍ وواضح وأقل ضجيجًا."]] },
    contact: { slug: "contact", eyebrow: "CONTACT", title: "طريق واضح\nإلى المساعدة.", summary: "ابدئي من السؤال الأقرب لك عبر الأدلة والأسئلة الشائعة وتتبع الطلب. ستظهر قنوات خدمة العملاء هنا فور اعتمادها وتشغيلها.", status: "نشارك فقط قنوات تواصل مؤكدة ويمكن الاعتماد عليها.", sections: [{ title: "المتاح الآن", body: "يمكنك الرجوع إلى الأسئلة الشائعة وصفحات السياسات وتتبع الطلب للوصول إلى المعلومة الأقرب لسؤالك.", points: ["الأسئلة الشائعة", "الثقة والسياسات", "تتبع الطلب"] }, { title: "قنوات الخدمة", body: "تُضاف وسيلة التواصل وساعات العمل وزمن الاستجابة وسياسة التصعيد بعد تشغيل قناة خدمة العملاء الرسمية." }], faqs: [["أين البريد أو رقم الهاتف؟", "لن ننشر قناة غير مؤكدة. ستظهر هنا فور تشغيلها والتحقق منها."], ["كيف أصل إلى المعلومة الآن؟", "ابدئي بالأسئلة الشائعة أو دليل الثقة، واستخدمي تتبع الطلب إذا كان لديك رقم طلب."]] },
    faq: { slug: "faq", eyebrow: "FREQUENTLY ASKED", title: "إجابات صريحة،\nبلا غموض.", summary: "إجابات مباشرة عن المنتجات والمحتوى والشراء والسياسات، مع فصل واضح بين المتاح الآن وما سيُعلن عند الإطلاق التجاري.", status: "إذا لم تُعتمد المعلومة بعد، نقول ذلك بوضوح.", sections: [{ title: "الشراء والدفع", body: "تظهر وسائل الدفع والأسعار والمخزون فقط عند تفعيل الكتالوج التجاري واعتماد بياناته." }, { title: "الشحن والإرجاع", body: "تُنشر التغطية والرسوم والمدد والاستثناءات من بيانات المزود والسياسة المعتمدة." }, { title: "المنتجات والمحتوى", body: "الصور المفاهيمية ليست منتجات للبيع، والمحتوى التعليمي لا يبدل استشارة مختص." }], faqs: [["هل أستطيع الشراء الآن؟", "ليس بعد. سيتاح الشراء عند اكتمال الكتالوج ومزودي الدفع والشحن والاعتمادات التشغيلية."], ["هل الأسعار المعروضة نهائية؟", "لا تظهر أسعار عامة قبل اعتماد الكتالوج التجاري."], ["هل الروتينات نصيحة طبية؟", "لا. هي معلومات عامة ولا تشخّص أو تعالج حالة."]] },
    terms: { slug: "terms", eyebrow: "TERMS", title: "شروط مفهومة،\nقبل الموافقة.", summary: "هذه ليست شروط بيع نهائية. يلزم اعتماد هوية المنشأة والدفع والشحن والإرجاع والاختصاص القانوني أولًا.", status: provisional.ar, sections: [{ title: "نطاق الاستخدام", body: "يمكن تصفح النموذج لأغراض العرض. لا ينشأ عقد بيع عام لأن التجارة غير مفعلة." }, { title: "المحتوى والملكية", body: "العلامات والأصول المعتمدة تبقى لأصحابها، والصور المفاهيمية موسومة ولا تمثل كتالوجًا." }, { title: "قبل الإطلاق التجاري", body: "تُراجع الأهلية والدفع والإلغاء والتوصيل والإرجاع والمسؤولية والاختصاص وآلية الشكاوى قانونيًا." }], faqs: [["هل هذه الشروط نافذة للبيع؟", "لا. هي هيكل مؤقت ولا يحل محل مراجعة قانونية معتمدة."], ["متى تصبح نهائية؟", "بعد اعتماد بيانات المنشأة والسياسات والمزودين وإصدار نسخة مؤرخة."]] },
  },
  en: {
    about: { slug: "about", eyebrow: "ABOUT ÉLORÉ", title: "Beauty, composed\nwith intention.", summary: "A digital beauty house pairing refined editorial sensibility with the clarity and rhythm of life in Saudi Arabia — so understanding belongs in every choice.", status: "Our story grows with the collection; our principle remains constant: beauty begins with clarity.", sections: [{ title: "The idea", body: "A quieter edit, clearer information and imagery that respects the truth before a decision." }, { title: "What we stand for", body: "No inflated promises, no product without verified detail, and no content that outruns the evidence behind it." }], faqs: [["What defines ÉLORÉ?", "A bilingual experience that connects beauty with understanding and gives each decision more clarity and calm."], ["Who is the experience for?", "Audiences in Saudi Arabia seeking refined, clearer and quieter beauty choices."]] },
    contact: { slug: "contact", eyebrow: "CONTACT", title: "A clear route\nto support.", summary: "Begin with the guide, FAQ or order-tracking route closest to your question. Customer-care channels will appear here as soon as they are verified and operational.", status: "We publish only confirmed contact routes you can rely on.", sections: [{ title: "Available now", body: "Use the FAQ, policy pages or order tracking to reach the information closest to your question.", points: ["Frequently asked questions", "Trust and policies", "Order tracking"] }, { title: "Customer-care channels", body: "Contact details, opening hours, response targets and escalation guidance will appear when the official service channel is operational." }], faqs: [["Where is the email or phone number?", "We will not publish an unverified channel. It will appear here as soon as it is operational and confirmed."], ["How can I find help now?", "Start with the FAQ or trust directory, and use order tracking if you have an order number."]] },
    faq: { slug: "faq", eyebrow: "FREQUENTLY ASKED", title: "Direct answers,\nwithout ambiguity.", summary: "Straight answers about products, guidance, purchasing and policies, with a clear line between what is available now and what follows at commercial launch.", status: "When information is not yet verified, we say so clearly.", sections: [{ title: "Purchasing and payment", body: "Payment methods, prices and stock appear only when the commercial catalog and its data are approved." }, { title: "Shipping and returns", body: "Coverage, fees, timing and exceptions are published from approved carrier data and policy." }, { title: "Products and guidance", body: "Concept imagery is not inventory, and educational content is not professional medical advice." }], faqs: [["Can I purchase now?", "Not yet. Checkout opens when the catalog, payment and shipping providers, and operating approvals are complete."], ["Are displayed prices final?", "No public prices appear before the commercial catalog is approved."], ["Are routines medical advice?", "No. They are general information and do not diagnose or treat a condition."]] },
    terms: { slug: "terms", eyebrow: "TERMS", title: "Terms you can\nunderstand before agreeing.", summary: "These are not final sales terms. The entity, payment, delivery, returns and governing framework must be approved first.", status: provisional.en, sections: [{ title: "Use of this prototype", body: "The experience can be browsed for demonstration. No public sales contract is formed because commerce is disabled." }, { title: "Content and ownership", body: "Approved marks and assets remain with their owners; labelled concept imagery is not a product catalog." }, { title: "Before commercial launch", body: "Eligibility, payment, cancellation, delivery, returns, liability, governing law and complaints require legal review." }], faqs: [["Are these terms effective for sales?", "No. They are a provisional structure and not a substitute for approved legal review."], ["When will they be final?", "After the entity, policies and providers are approved and a dated version is issued."]] },
  },
};

export const trustHubCopy = {
  ar: { eyebrow: "TRUST DIRECTORY", title: "الثقة ليست\nشارة.", intro: "هي بيانات وسياسات وأدلة يمكن فهمها ومراجعتها قبل أن نطلب منك قرارًا.", directory: "دليل الثقة", principlesTitle: "ما نعرفه.\nوما ينتظر الاعتماد.", closeTitle: "الوضوح قبل\nالتجارة.", open: "افتحي الملف", support: "الأسئلة الشائعة", notice: provisional.ar },
  en: { eyebrow: "TRUST DIRECTORY", title: "Trust is not\na badge.", intro: "It is information, policy and evidence you can understand and review before we ask for a decision.", directory: "Trust directory", principlesTitle: "What we know.\nWhat awaits approval.", closeTitle: "Clarity before\ncommerce.", open: "Open record", support: "Frequently asked questions", notice: provisional.en },
} as const;

export function getTrustRecord(locale: Locale, slug: string) {
  return trustSlugs.includes(slug as TrustSlug) ? trustContent[locale][slug as TrustSlug] : null;
}

export function getSupportRecord(locale: Locale, slug: string) {
  return supportSlugs.includes(slug as SupportSlug) ? supportContent[locale][slug as SupportSlug] : null;
}
