import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CinematicKnowledgeStory } from "@/components/cinematic-knowledge-story";
import { StorefrontShell } from "@/components/storefront-shell";
import { absoluteUrl, getConcernByHref, getIngredientBySlug, getProductsBySlugs, getRoutineByHref, ingredients, journalArticles } from "@/lib/site-content";

type Props = { params: Promise<{ slug: string }> };
export async function generateStaticParams() { return ingredients.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const item = getIngredientBySlug((await params).slug); return item ? { title: `${item.title} | حسب المكوّن`, description: item.answer, alternates: { canonical: `/ingredients/${item.slug}` } } : {}; }

export default async function Page({ params }: Props) {
  const ingredient = getIngredientBySlug((await params).slug); if (!ingredient) notFound();
  const products = getProductsBySlugs(ingredient.productSlugs); const routines = ingredient.relatedRoutineHrefs.map(getRoutineByHref).filter((item): item is NonNullable<typeof item> => Boolean(item)); const concerns = ingredient.relatedConcernHrefs.map(getConcernByHref).filter((item): item is NonNullable<typeof item> => Boolean(item)); const articles = journalArticles.filter((article) => ingredient.articleSlugs.includes(article.slug));
  const related = products.map((product) => ({ label: product.name, meta: product.category, href: `/products/${product.slug}`, type: "product" })).concat(routines.map((routine) => ({ label: routine.title, meta: "روتين", href: `/routines/${routine.slug}`, type: "routine" })), concerns.map((concern) => ({ label: concern.title, meta: "حسب المشكلة", href: `/concerns/${concern.slug}`, type: "concern" })), articles.map((article) => ({ label: article.title, meta: article.category, href: `/journal/${article.slug}`, type: "article" })));
  const primaryHref = products[0] ? `/products/${products[0].slug}` : routines[0] ? `/routines/${routines[0].slug}` : "/ingredients";
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "CollectionPage", name: ingredient.title, description: ingredient.summary, url: absoluteUrl(`/ingredients/${ingredient.slug}`), inLanguage: "ar-SA" }, { "@type": "ItemList", itemListElement: products.map((product, index) => ({ "@type": "ListItem", position: index + 1, name: product.name, url: absoluteUrl(`/products/${product.slug}`) })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "الرئيسية", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "المكوّنات", item: absoluteUrl("/ingredients") }, { "@type": "ListItem", position: 3, name: ingredient.title, item: absoluteUrl(`/ingredients/${ingredient.slug}`) }] }, { "@type": "FAQPage", mainEntity: ingredient.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }] };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><StorefrontShell activeHref="/ingredients"><CinematicKnowledgeStory kind="ingredient" slug={ingredient.slug} eyebrow={ingredient.subtitle} title={ingredient.title} summary={ingredient.summary} answer={ingredient.answer} signals={[ingredient.role, ...ingredient.fitNotes]} chapterEyebrow="متى يناسبك؟" chapterTitle="الدور أوضح داخل سياق حقيقي." items={ingredient.fitNotes.map((note, index) => ({ label: String(index + 1).padStart(2, "0"), title: `إشارة ملاءمة ${index + 1}`, copy: note }))} watchTitle="الحدود جزء من فهم المكوّن." watchItems={ingredient.watchouts} related={related} faqs={ingredient.faqs} backHref="/ingredients" backLabel="كل المكوّنات" primaryHref={primaryHref} primaryLabel="شاهدي أقرب اختيار" /></StorefrontShell></>;
}
