import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CinematicKnowledgeStory } from "@/components/cinematic-knowledge-story";
import { StorefrontShell } from "@/components/storefront-shell";
import { absoluteUrl, concerns, getConcernBySlug, getIngredientByName, getProductsBySlugs, journalArticles } from "@/lib/site-content";

type Props = { params: Promise<{ slug: string }> };
export async function generateStaticParams() { return concerns.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const item = getConcernBySlug((await params).slug); return item ? { title: `${item.title} | حسب المشكلة`, description: item.answer, alternates: { canonical: `/concerns/${item.slug}` } } : {}; }

export default async function Page({ params }: Props) {
  const concern = getConcernBySlug((await params).slug); if (!concern) notFound();
  const products = getProductsBySlugs(concern.products); const articles = journalArticles.filter((article) => article.relatedConcern === `/concerns/${concern.slug}`);
  const related = products.map((product) => ({ label: product.name, meta: product.category, href: `/products/${product.slug}`, type: "product" })).concat(articles.map((article) => ({ label: article.title, meta: article.category, href: `/journal/${article.slug}`, type: "article" })), [{ label: concern.routineLabel, meta: "روتين مقترح", href: concern.routineHref, type: "routine" }]);
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "CollectionPage", name: concern.title, description: concern.summary, url: absoluteUrl(`/concerns/${concern.slug}`), inLanguage: "ar-SA" }, { "@type": "ItemList", itemListElement: products.map((product, index) => ({ "@type": "ListItem", position: index + 1, name: product.name, url: absoluteUrl(`/products/${product.slug}`) })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "الرئيسية", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "حسب المشكلة", item: absoluteUrl("/concerns") }, { "@type": "ListItem", position: 3, name: concern.title, item: absoluteUrl(`/concerns/${concern.slug}`) }] }, { "@type": "FAQPage", mainEntity: concern.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }] };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><StorefrontShell activeHref="/concerns"><CinematicKnowledgeStory kind="concern" slug={concern.slug} eyebrow={concern.subtitle} title={concern.title} summary={concern.summary} answer={concern.answer} signals={concern.keyIngredients} chapterEyebrow="مكوّنات القرار" chapterTitle="ابدئي بالأدوار الأكثر منطقية." items={concern.keyIngredients.map((name, index) => { const ingredient = getIngredientByName(name); return { label: String(index + 1).padStart(2, "0"), title: name, copy: ingredient?.role ?? "مكوّن داعم يُفهم ضمن الروتين الكامل، لا كوعد منفصل.", href: ingredient ? `/ingredients/${ingredient.slug}` : undefined }; })} watchTitle="التحسن الهادئ يحتاج توقعات واقعية." watchItems={["لا تحوّلي المشكلة إلى تشخيص ذاتي.", "اختبري المنتجات الجديدة تدريجيًا.", "استشيري مختصًا عند التهيج المستمر أو الأعراض المقلقة."]} related={related} faqs={concern.faqs} backHref="/concerns" backLabel="كل المشكلات" primaryHref={concern.routineHref} primaryLabel="ابدئي الروتين المقترح" /></StorefrontShell></>;
}
